version: '2'
services:
  elasticsearch:
    image: elasticsearch:6.5.4
    ports:
      - 9200:9200
      - 9300:9300
    # volumes:
    #   - ./db/:/opt/db/
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
